<HTML>
<b> Isabelli Lima Alves n14,1B</b>
<p>/HTML Olá,meu nome é Isabelli Lima.Criei esse meu site para desenvolver meus projetos do Github,me aprofundar na Robótica e aprender como funciona cada
elemento daqui.Irei expecializar cada dia mais na computação e seus fundamentos,adquirir conhecimentos robóticos e com esses conhecimentos poder elevar 
minha carreira profissional.
index.html
